/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tEHhMFy1eS6
 */
import { Button } from "@/components/ui/button"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { JSX, SVGProps } from "react"

export function GuestinforUpload() {
  return (
    <div className="flex flex-col items-center justify-center p-4">
      <div className="flex items-center space-x-2 mb-4">
        <FlagIcon className="text-blue-600 h-8 w-8" />
        <span className="text-xl font-bold">FNM</span>
      </div>
      <div className="flex justify-end w-full mb-4">
        <Button className="bg-blue-600 text-white">로그인</Button>
        <Avatar>
          <AvatarImage alt="User profile" src="/placeholder.svg?height=32&width=32" />
          <AvatarFallback>U</AvatarFallback>
        </Avatar>
      </div>
      <div className="w-full max-w-4xl">
        <div className="flex justify-between items-center mb-2">
          <h1 className="text-2xl font-semibold">입주자 정보 업로드</h1>
          <div className="flex space-x-2">
            <Button variant="outline">업로드 방법</Button>
            <Button variant="outline">샘플 다운로드</Button>
          </div>
        </div>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="w-[100px]">전화번호</TableHead>
              <TableHead>이름</TableHead>
              <TableHead>동</TableHead>
              <TableHead>호수</TableHead>
              <TableHead>선택</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell>1</TableCell>
              <TableCell />
              <TableCell />
              <TableCell />
              <TableCell />
            </TableRow>
            <TableRow>
              <TableCell>2</TableCell>
              <TableCell />
              <TableCell />
              <TableCell />
              <TableCell />
            </TableRow>
            <TableRow>
              <TableCell>010-1234-5678</TableCell>
              <TableCell>홍길동</TableCell>
              <TableCell>123동</TableCell>
              <TableCell>603호수</TableCell>
              <TableCell>
                <CheckIcon className="h-6 w-6" />
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>4</TableCell>
              <TableCell />
              <TableCell />
              <TableCell />
              <TableCell />
            </TableRow>
            <TableRow>
              <TableCell>5</TableCell>
              <TableCell />
              <TableCell />
              <TableCell />
              <TableCell />
            </TableRow>
            <TableRow>
              <TableCell>6</TableCell>
              <TableCell />
              <TableCell />
              <TableCell />
              <TableCell />
            </TableRow>
            <TableRow>
              <TableCell>7</TableCell>
              <TableCell />
              <TableCell />
              <TableCell />
              <TableCell />
            </TableRow>
            <TableRow>
              <TableCell>8</TableCell>
              <TableCell />
              <TableCell />
              <TableCell />
              <TableCell />
            </TableRow>
          </TableBody>
        </Table>
        <div className="flex justify-between items-center mt-4">
          <Button variant="secondary">수정</Button>
          <Button variant="secondary">삭제</Button>
          <Button>완료</Button>
        </div>
      </div>
    </div>
  )
}


function FlagIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}


function CheckIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  )
}
