/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/y1woKs42B8D
 */
import { Button } from "@/components/ui/button"
import { AvatarImage, Avatar } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function NoticeWrite() {
  return (
    <div key="1" className="min-h-screen bg-gray-100 p-8">
      <header className="flex justify-between items-center">
        <h1 className="text-xl font-bold text-blue-600">FNM</h1>
        <div className="flex items-center space-x-4">
          <Button className="bg-blue-500 text-white py-2 px-4 rounded-md">로그아웃</Button>
          <Avatar>
            <AvatarImage alt="User profile" src="/placeholder.svg?height=40&width=40" />
          </Avatar>
        </div>
      </header>
      <main className="mt-8">
        <section className="bg-white p-8 rounded-md shadow-md">
        <div className="flex justify-between items-center mb-2">
          <h2 className="text-3xl font-semibold mb-4">공지사항</h2>
          <div className="flex space-x-2">
            <Button className="ml-auto">목록</Button>
          </div>
          
        </div>
          <div className="grid grid-cols-2 gap-4 mb-4">
            <div className="flex flex-col">
              <label className="mb-2 font-medium" htmlFor="title">
                제목 :
              </label>
              <Input id="title" placeholder="알림하세요." />
            </div>
            <div className="flex flex-col">
              <label className="mb-2 font-medium" htmlFor="date">
                날짜 :
              </label>
              <Input id="date" placeholder="2023.10.10" />
            </div>
          </div>
          <div className="flex flex-col">
            <label className="mb-2 font-medium" htmlFor="content">
              내용 :
            </label>
            <Textarea className="h-64" id="content" placeholder="알림하세요." />
          </div>
          <div className="mt-4 flex justify-end">
            <Button className="bg-gray-300 text-black py-2 px-6 rounded-md">작성</Button>
          </div>
        </section>
      </main>
    </div>
  )
}
