/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2bVEcH4SRKE
 */
import { Button } from "@/components/ui/button"
import { JSX, SVGProps } from "react"

export function Notice() {
  return (
    <div className="max-w-4xl mx-auto my-10">
      <div className="flex items-center justify-between mb-8">
        <div className="flex items-center space-x-2">
          <div className="bg-[#3751FF] p-2 rounded-md">
            <FacebookIcon className="text-white" />
          </div>
          <span className="text-xl font-bold">FNM</span>
        </div>
        <Button className="bg-white border border-gray-300 shadow-sm">
          <UserIcon className="text-blue-600" />
          로그아웃
        </Button>
      </div>
      <h1 className="text-3xl font-bold mb-6">공지사항</h1>
      <div className="border-t border-b divide-y">
        <div className="flex justify-between items-center py-4">
          <div>
            <h2 className="text-lg font-semibold">아파트 입주 전자</h2>
            <p className="text-gray-500">2023.10.10</p>
          </div>
          <div className="flex items-center space-x-3">
            <FileEditIcon className="text-gray-500 cursor-pointer" />
            <DeleteIcon className="text-red-500 cursor-pointer" />
          </div>
        </div>
        <div className="flex justify-between items-center py-4">
          <div>
            <h2 className="text-lg font-semibold">이사 예약 확인 방법 안내</h2>
            <p className="text-gray-500">2023.10.10</p>
          </div>
          <div className="flex items-center space-x-3">
            <FileEditIcon className="text-gray-500 cursor-pointer" />
            <DeleteIcon className="text-red-500 cursor-pointer" />
          </div>
        </div>
        <div className="flex justify-between items-center py-4">
          <div>
            <h2 className="text-lg font-semibold">1차 하자 신고 안심 및 방법</h2>
            <p className="text-gray-500">2023.10.10</p>
          </div>
          <div className="flex items-center space-x-3">
            <FileEditIcon className="text-gray-500 cursor-pointer" />
            <DeleteIcon className="text-red-500 cursor-pointer" />
          </div>
        </div>
        <div className="flex justify-between items-center py-4">
          <div>
            <h2 className="text-lg font-semibold">아파트 대표자 선거 일정을 시작 새로</h2>
            <p className="text-gray-500">2023.10.10</p>
          </div>
          <div className="flex items-center space-x-3">
            <FileEditIcon className="text-gray-500 cursor-pointer" />
            <DeleteIcon className="text-red-500 cursor-pointer" />
          </div>
        </div>
      </div>
      <div className="flex items-center justify-center mt-8">
        <Button className="bg-blue-600 text-white rounded-full p-4">
          <PlusIcon className="text-white" />
        </Button>
      </div>
      <div className="flex justify-center mt-10">
        <Button className="bg-blue-600 text-white px-10 py-2 rounded-lg">공지사항 더 찾아보기</Button>
      </div>
    </div>
  )
}


function FacebookIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function UserIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function FileEditIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 13.5V4a2 2 0 0 1 2-2h8.5L20 7.5V20a2 2 0 0 1-2 2h-5.5" />
      <polyline points="14 2 14 8 20 8" />
      <path d="M10.42 12.61a2.1 2.1 0 1 1 2.97 2.97L7.95 21 4 22l.99-3.95 5.43-5.44Z" />
    </svg>
  )
}


function DeleteIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 5H9l-7 7 7 7h11a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2Z" />
      <line x1="18" x2="12" y1="9" y2="15" />
      <line x1="12" x2="18" y1="9" y2="15" />
    </svg>
  )
}


function PlusIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
