/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/9wsDYLhX6qg
 */
import { Button } from "@/components/ui/button"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { JSX, SVGProps } from "react"

export function ReservationConfirm() {
  return (
    <div className="max-w-4xl mx-auto p-6 bg-white">
      <header className="flex justify-between items-center mb-6">
        <div className="flex items-center space-x-2">
          <div className="bg-blue-600 p-2 rounded">
            <FlagIcon className="text-white" />
          </div>
          <span className="text-xl font-bold">FNM</span>
        </div>
        <Button className="flex items-center space-x-2" variant="ghost">
          <LogOutIcon className="text-blue-600" />
          <span className="text-blue-600">로그아웃</span>
        </Button>
      </header>
      <main>
        <div className="grid grid-cols-2 gap-6">
          <Card className="col-span-1">
            <CardHeader>
              <CardTitle>동 · 호수</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-lg font-medium">***동****호</p>
              <p className="mt-4 text-sm">이사 정보</p>
              <p>***시부터 ***시까지</p>
            </CardContent>
          </Card>
          <Card className="col-span-1">
            <CardHeader>
              <CardTitle>이사 날짜</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-lg font-medium">2023년10월10일</p>
              <p className="mt-4 text-sm">연락처: 원룸빌딩</p>
              <p>전화 : 053-324-3252</p>
              <p className="mt-4 text-sm">사다리차 이용</p>
              <p>엘리베이터 이용</p>
            </CardContent>
          </Card>
        </div>
        <div className="flex justify-between items-center mt-6">
          <Button>확인</Button>
          <Button variant="outline">예약 변경</Button>
        </div>
      </main>
    </div>
  )
}


function FlagIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}


function LogOutIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
      <polyline points="16 17 21 12 16 7" />
      <line x1="21" x2="9" y1="12" y2="12" />
    </svg>
  )
}
