/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ygDc2qx65x4
 */
import { Button } from "@/components/ui/button"
import { AvatarImage, Avatar } from "@/components/ui/avatar"
import { Calendar } from "@/components/ui/calendar"
import { Checkbox } from "@/components/ui/checkbox"
import { Textarea } from "@/components/ui/textarea"
import { TableHead, TableRow, TableHeader, TableBody, Table } from "@/components/ui/table"
import { Input } from "@/components/ui/input"
import { JSX, SVGProps } from "react"

export function Reservation() {
  return (
    <div className="max-w-4xl mx-auto">
      <div className="flex items-center justify-between p-4">
      <div className="flex items-center justify-between">
        <h1 className="text-xl font-bold text-blue-600">FNM</h1>
        
      </div>
      </div>
      <div className="flex flex-col md:flex-row md:space-x-8">
        <div className="flex flex-col items-center">
          <div className="p-4">
            
            
            <Calendar className="rounded-md border" mode="single" />
          </div>
          <div className="mt-4 p-4 w-full">
            <h3 className="text-lg font-semibold">이사 방식</h3>
            <div className="flex items-center space-x-2 my-2">
              <Checkbox id="start-use" />
              <label className="text-sm font-medium" htmlFor="start-use">
                사다리차 이용
              </label>
            </div>
            <div className="flex items-center space-x-2 my-2">
              <Checkbox id="elevator-use" />
              <label className="text-sm font-medium" htmlFor="elevator-use">
                엘리베이터 이용
              </label>
            </div>
            <Textarea placeholder="요청사항" />
            <Button className="mt-4">다음</Button>
          </div>
        </div>
        <div className="flex-1">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[100px]">9시~12시</TableHead>
                <TableHead className="w-[100px]">12시~15시</TableHead>
                <TableHead className="w-[100px]">15시~18시</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody />
          </Table>
          <p className="text-sm mt-4">-원하시는 이용을 위해 지정 시간 최소 3시간이라는 점 양지 부탁드립니다.</p>
          <div className="flex items-center space-x-2 mt-4">
            <Input className="w-20" placeholder="오전" type="text" />
            <span>**</span>
            <Input className="w-20" placeholder="분" type="text" />
            <span>**</span>
            <Input className="w-20" placeholder="까지" type="text" />
          </div>
        </div>
      </div>
    </div>
  )
}


function ChevronLeftIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
