/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ANHYCRoqJIM
 */
import { Button } from "@/components/ui/button"
import { JSX, SVGProps } from "react"

export function fnm() {
  return (
    <div className="max-w-4xl mx-auto my-8 p-4">
      <div className="flex justify-between items-center mb-4">
        <h1 className="text-3xl font-bold text-blue-600">FNM</h1>
        <Button className="bg-blue-600 text-white">로그인</Button>
      </div>
      <div className="flex justify-between space-x-4 mb-6">
        <Button className="flex-1 text-center border-b-2 border-blue-600 py-2">오늘 예약</Button>
        <Button className="flex-1 text-center py-2">내일 예약</Button>
        <Button className="flex-1 text-center py-2">전날 예약</Button>
      </div>
      <div className="mb-6">
        <h2 className="text-lg font-semibold flex items-center">
          공지사항
          <SpeakerIcon className="ml-2 w-5 h-5" />
        </h2>
        <div className="mt-4">
          <div className="border-t border-b py-2">
            <h3 className="font-medium">아파트 입주 전화</h3>
            <p className="text-sm">이사 예약 확인 및 방법 안내</p>
            <p className="text-sm">2023.10.10</p>
          </div>
          <div className="border-b py-2">
            <h3 className="font-medium">1차 하자 신고 약속 및 방법</h3>
            <p className="text-sm">2023.10.10</p>
          </div>
        </div>
      </div>
      <div className="border rounded-lg p-4">
        <h3 className="text-lg font-semibold mb-4">이사 예약/확인</h3>
        <div className="flex justify-center items-center">
          <CheckIcon className="w-24 h-24" />
        </div>
      </div>
    </div>
  )
}


function SpeakerIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="16" height="20" x="4" y="2" rx="2" ry="2" />
      <circle cx="12" cy="14" r="4" />
      <line x1="12" x2="12.01" y1="6" y2="6" />
    </svg>
  )
}


function CheckIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  )
}
