/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Vn92PZef71p
 */
import { Button } from "@/components/ui/button"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { JSX, SVGProps } from "react"

export function Mastermain() {
  return (
    <div className="bg-white p-8">
      <div className="flex items-center justify-between mb-6">
      <h1 className="text-xl font-bold text-blue-600">FNM</h1>
        <div className="flex items-center space-x-4">
          <SettingsIcon className="h-6 w-6 text-gray-600" />
          <Avatar>
            <AvatarImage alt="profile" src="/placeholder.svg?height=32&width=32" />
            <AvatarFallback>?</AvatarFallback>
          </Avatar>
        </div>
      </div>
      <div className="flex justify-between space-x-4 mb-8">
        <Button className="flex-1" variant="outline">
          오늘 예약
        </Button>
        <Button className="flex-1" variant="outline">
          내일 예약
        </Button>
        <Button className="flex-1" variant="outline">
          전날 예약
        </Button>
      </div>
      <div className="grid grid-cols-2 gap-4">
        <Card className="w-full">
          <CardHeader>
            <CardTitle>공지사항 수정</CardTitle>
          </CardHeader>
          <CardContent className="flex justify-center items-center">
            <AlertCircleIcon className="h-12 w-12 text-red-500" />
          </CardContent>
        </Card>
        <Card className="w-full">
          <CardHeader>
            <CardTitle>유저 정보 업로드</CardTitle>
          </CardHeader>
          <CardContent className="flex justify-center items-center">
            <UploadIcon className="h-12 w-12 text-gray-600" />
          </CardContent>
        </Card>
        <Card className="w-full">
          <CardHeader>
            <CardTitle>예약 확인</CardTitle>
          </CardHeader>
          <CardContent className="flex justify-center items-center">
            <CheckIcon className="h-12 w-12 text-gray-600" />
          </CardContent>
        </Card>
        <Card className="w-full">
          <CardHeader>
            <CardTitle>동/호수 생성</CardTitle>
          </CardHeader>
          <CardContent className="flex justify-center items-center">
            <PlusIcon className="h-12 w-12 text-gray-600" />
          </CardContent>
        </Card>
      </div>
    </div>
  )
}


function SettingsIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function AlertCircleIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <line x1="12" x2="12" y1="8" y2="12" />
      <line x1="12" x2="12.01" y1="16" y2="16" />
    </svg>
  )
}


function UploadIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  )
}


function CheckIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  )
}


function PlusIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
