/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2BbR8PSYcMw
 */

import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { AvatarImage, Avatar } from "@/components/ui/avatar"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { JSX, SVGProps } from "react"

export function MasterGuestStatus() {
  return (
    <div key="1" className="max-w-4xl mx-auto my-8 p-6 bg-white shadow rounded-md">
      <div className="max-w-4xl mx-auto my-8 p-6 bg-white shadow rounded-md">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center space-x-4">

            <h1 className="text-xl font-bold">FNM</h1>
          </div>
          <div className="flex items-center space-x-4">

            <Input className="border p-2 rounded" placeholder="검색어" />
            <Button variant="secondary">검색</Button>
            <Avatar>

              <AvatarImage alt="User profile" src="/placeholder.svg?height=32&width=32" />
            </Avatar>
            <Button className="bg-white border border-gray-300 shadow-sm">
          <UserIcon className="text-blue-600" />
          로그아웃
        </Button>
          </div>
        </div>
        <div className="flex justify-between mb-6">
          <Button className="w-1/4" variant="outline">
            동/호수 생성
          </Button>
          <Button className="w-1/4" variant="outline">
            예약 확인
          </Button>
          <Button className="w-1/4" variant="outline">
            입주 현황
          </Button>
        </div>
        <Table>
          <TableBody>
            <TableRow>

              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
            </TableRow>
          </TableBody>
          <TableBody>
            <TableRow>

              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
            </TableRow>
          </TableBody>
          <TableBody>
            <TableRow>

              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
            </TableRow>
          </TableBody>
          <TableBody>
            <TableRow>

              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
            </TableRow>
          </TableBody>
          <TableBody>
            <TableRow>

              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
            </TableRow>
          </TableBody>
          <TableBody>
            <TableRow>

              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
            </TableRow>
          </TableBody>
          <TableBody>
            <TableRow>

              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
            </TableRow>
          </TableBody>
          <TableBody>
            <TableRow>

              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
            </TableRow>
          </TableBody>
          <TableBody>
            <TableRow>

              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
            </TableRow>
          </TableBody>
          <TableBody>
            <TableRow>

              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
            </TableRow>
          </TableBody>
          <TableBody>
            <TableRow>

              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
            </TableRow>
          </TableBody>
          <TableBody>
            <TableRow>

              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
              <TableCell>***호</TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    </div>
  )
}



function FlagIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}

function UserIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}